### ISSUE TITLE
Project openen na aanmaken

### ISSUE THREAD

**Issue by jgroenen** [Algoritmeregister/beheertool#16]
Als algoritme expert
Wil ik bij het aanmaken van een nieuw project direct naar dat project gaan
Zodat ik het niet eerst hoef te zoeken in het projectenoverzicht

**Comment by jgroenen** [comment]
Schijnbaar opent nu een ander project

**Comment by AnneSchoenmakers** [comment]
Ik heb net een nieuw test project aangemaakt, en na het opslaan blijft hij in hetzelfde scherm.
