### ISSUE TITLE
Algoritme toevoegen

### ISSUE THREAD

**Issue by jgroenen** [Algoritmeregister/beheertool#17]
Als algoritme expert
Wil ik een algoritme toevoegen (opslaan)
Maar ik krijg de melding "gegevens ophalen" en zie vervolgens het algoritme niet bij het project
In het overzicht van algoritmes zie ik het algoritme wel 3x staan

**Comment by VincentvanStiphout** [comment]
Dit probleem is opgelost, kan geaccepteerd worden.

**Comment by AnneSchoenmakers** [comment]
Ik heb net een nieuw algoritme toegevoegd binnen een nieuw aangemaakt test project maar ik krijg het nieuwe test algoritme niet te zien...
