### ISSUE TITLE
Wijzigingen worden niet opgeslagen

### ISSUE THREAD

**Issue by jgroenen** [Algoritmeregister/beheertool#18]
Als algoritme expert
Wil ik een wijziging opslaan
Maar als ik op de knop "Opslaan" klik verdwijnt de tekst die ik net heb toegevoegd

(volgens mij vooral bij de tekstvakken, zoals "databronnen" en "lange omschrijving")

**Comment by VincentvanStiphout** [comment]
Dit issue is opgelost, klaar voor acceptatie
